"""
Builds MASTER_VARIABLES.csv for the Odisha flood-data-ecosystem model.

Pulls together:
  - monthly variables  (tenders, rainfall, runoff, inundation, ...)
  - annual variables    (population, sex ratio, ...)
  - one-time variables  (schools, roads, drainage density, ...)
into a single object_id x timeperiod master table.

Assumes Sources/master/*.csv has already been generated by the
Sources-level builder script (the one that walks BHUVAN/IMD/NRSC/etc.
and writes flat per-variable CSVs into Sources/master/).
"""

import os
import glob
import re
import warnings

import geopandas as gpd
import pandas as pd

warnings.filterwarnings("ignore")

VARIABLES_DATA_PATH = os.getcwd() + '/Sources/master/'
SHAPEFILE_PATH = (
    '/Users/stephensmathew/cdl_rep/flood-data-ecosystem-Odisha/'
    'Maps/od_ids-drr_shapefiles/odisha_block_final.geojson'
)

DATE_RANGE = pd.date_range(start="2021-04-01", end="2026-08-30", freq='MS')
TIMEPERIODS = [d.strftime('%Y_%m') for d in DATE_RANGE]

MONTHLY_VARIABLES = [
    'total_tender_awarded_value',
    'SDMF_tenders_awarded_value',
    'SDRF_tenders_awarded_value',
    'RIDF_tenders_awarded_value',
    'Preparedness Measures_tenders_awarded_value',
    'Immediate Measures_tenders_awarded_value',
    'Others_tenders_awarded_value',
    'rainfall',
    'runoff',
    'inundation_pct',
]

ANNUAL_VARIABLES = [
    'mean_sex_ratio',
    'sum_aged_population',
    'sum_young_population',
    'sum_population',
]

ONETIME_VARIABLES = [
    'Schools',
    'RailLengths',
    'RoadLengths',
    'HealthCenters',
    'slope_elevation',
    'antyodaya_variables',
    'drainage_density',
    'distance_from_river',
    'distance_from_sea',
]


def load_monthly_variable(base_path: str, variable: str) -> pd.DataFrame:
    """
    Load a monthly variable's data. Handles two possible layouts:
      1. A single flat file: '<variable>.csv' with object_id + timeperiod columns.
      2. Per-month files: '<variable>_YYYY_MM.csv', with timeperiod encoded
         in the filename rather than as a column.
    Prefers (1) since Sources/master/ is expected to hold flat, already-merged
    files; falls back to (2) only if no flat file exists.
    """
    flat_path = base_path + variable + '.csv'
    if os.path.exists(flat_path):
        df = pd.read_csv(flat_path, encoding='utf-8-sig')
        if 'timeperiod' not in df.columns:
            print(f"Warning: {variable}.csv has no timeperiod column — "
                  f"treating as static, will broadcast to all months")
        return df

    monthly_files = glob.glob(base_path + f'{variable}_*.csv')
    if not monthly_files:
        raise FileNotFoundError(
            f"No file found for variable '{variable}' at {flat_path} "
            f"or {base_path}{variable}_*.csv"
        )

    dfs = []
    for f in monthly_files:
        m = re.search(r'_(\d{4}_\d{2})\.csv$', f)
        if not m:
            print(f"Warning: couldn't parse timeperiod from {f}, skipping")
            continue
        d = pd.read_csv(f, encoding='utf-8-sig')
        d['timeperiod'] = m.group(1)
        dfs.append(d)

    if not dfs:
        raise FileNotFoundError(
            f"Found files matching {variable}_*.csv but couldn't parse "
            f"timeperiod from any of them."
        )
    return pd.concat(dfs, ignore_index=True)


def build_base_grid() -> pd.DataFrame:
    """One row per (block, timeperiod) across the full date range."""
    od_sd = gpd.read_file(SHAPEFILE_PATH)
    dfs = []
    for period in TIMEPERIODS:
        df = od_sd[['block_name', 'object_id', 'block_area', 'dtname']].copy()
        df.columns = ['block_name', 'object_id', 'block_area', 'district']
        df['timeperiod'] = period
        dfs.append(df)
    return pd.concat(dfs).reset_index(drop=True)


def merge_monthly_variables(master_df: pd.DataFrame) -> pd.DataFrame:
    for variable in MONTHLY_VARIABLES:
        print(variable)
        variable_df = load_monthly_variable(VARIABLES_DATA_PATH, variable)
        variable_df = variable_df.drop_duplicates()

        if 'object_id' not in variable_df.columns:
            raise KeyError(
                f"{variable} data is missing key 'object_id'. "
                f"Columns present: {variable_df.columns.tolist()}"
            )
        merge_keys = ['object_id', 'timeperiod'] if 'timeperiod' in variable_df.columns else ['object_id']

        master_df = master_df.merge(variable_df, on=merge_keys, how='left')
        master_df = master_df.drop(columns=master_df.filter(regex='_x$|_y$').columns)
    return master_df


def merge_annual_variables(master_df: pd.DataFrame) -> pd.DataFrame:
    master_df['year'] = master_df['timeperiod'].str[:4].astype(int)
    for variable in ANNUAL_VARIABLES:
        variable_df = pd.read_csv(VARIABLES_DATA_PATH + variable + '.csv', encoding='utf-8-sig')
        variable_df = variable_df.rename(columns={'timeperiod': 'year'})
        master_df = master_df.merge(variable_df, on=['object_id', 'year'], how='left')
    return master_df


def merge_onetime_variables(master_df: pd.DataFrame) -> pd.DataFrame:
    master_df['year'] = ''
    for variable in ONETIME_VARIABLES:
        print(variable)
        variable_df = pd.read_csv(VARIABLES_DATA_PATH + variable + '.csv', encoding='utf-8-sig')
        variable_df['year'] = ''
        print(f"master_df shape: {master_df.shape}")
        print(f"variable_df shape: {variable_df.shape}")
        master_df = master_df.merge(variable_df, on=['object_id', 'year'], how='left')
        master_df = master_df.drop(columns=master_df.filter(regex='_y$').columns)
        master_df.columns = master_df.columns.str.replace('_x$', '', regex=True)
    return master_df


def impute_group_means(master_df: pd.DataFrame) -> pd.DataFrame:
    # Rain/runoff: fill missing with the object_id's own mean
    for col in ['max_rain', 'mean_rain', 'sum_rain',
                'Sum_Runoff', 'Peak_Runoff', 'Mean_Daily_Runoff']:
        master_df[col] = master_df[col].fillna(
            master_df.groupby(['object_id'])[col].transform('mean')
        )

    # ANTYODAYA vars: fill missing with the district's mean/median
    master_df['block_nosanitation_hhds_pct'] = master_df['block_nosanitation_hhds_pct'].fillna(
        master_df.groupby(['district'])['block_nosanitation_hhds_pct'].transform('mean'))
    master_df['block_piped_hhds_pct'] = master_df['block_piped_hhds_pct'].fillna(
        master_df.groupby(['district'])['block_piped_hhds_pct'].transform('mean'))
    master_df['avg_tele'] = master_df['avg_tele'].fillna(
        master_df.groupby(['district'])['avg_tele'].transform('median'))
    master_df['avg_electricity'] = master_df['avg_electricity'].fillna(
        master_df.groupby(['district'])['avg_electricity'].transform('mean'))
    master_df['net_sown_area_in_hac'] = master_df['net_sown_area_in_hac'].fillna(
        master_df.groupby(['district'])['net_sown_area_in_hac'].transform('mean'))
    return master_df


def main():
    master_df = build_base_grid()
    print(master_df)

    master_df = merge_monthly_variables(master_df)
    master_df = merge_annual_variables(master_df)

    zero_counts = master_df.apply(lambda x: (x == 0).sum())
    print(zero_counts)
    print(master_df.columns)

    master_df = merge_onetime_variables(master_df)
    master_df = master_df.drop(['year', 'count_bhuvan_pixels', 'count_inundated_pixels'], axis=1)
    print(master_df.columns)

    master_df = impute_group_means(master_df)

    # Impute everything else with 0
    master_df = master_df.fillna(0)
    master_df = master_df.loc[:, ~master_df.columns.str.endswith('_x') & ~master_df.columns.str.endswith('_y')]

    master_df.to_csv(os.getcwd() + '/MASTER_VARIABLES.csv', index=False)
    print(master_df.shape)


if __name__ == '__main__':
    main()